baseURL = 'https://arbs09.dev'

languageCode = 'en'
defaultContentLanguage = "en"

title = 'arbs09 Blog'
copyright = "arbs09"
auther = "arbs09"
theme = "tailwind"

enableRobotsTXT = true
enableEmoji = true

[markup]
  _merge = "deep"
  [markup.highlight]
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.cjk]
        enable = true
        eastAsianLineBreaks = true
        escapedSpace = true


[params]

  keywords = "arbs09, dev blog, blog, developer, html, python, pyguard"
  subtitle = "arbs09 dev Blog"
  contentTypeName = "posts"
  jsonLD = true
  showAuthor = true
  [author]
    name = "arbs09"
    email = "hi@arbs09.dev"

  [params.header]
    logo = "logo.webp"

  [params.footer]
    since = 2024
    poweredby = true

  [parms.social_media]
  [[params.social_media.items]]
    enabled = true
    title = 'Github'
    icon = 'brand-github'
    link = 'https://github.com/arbs09/'

  [[params.social_media.items]]
    enabled = true
    title = 'Instagram'
    icon = 'brand-instagram'
    link = 'https://instagram.com/arbs09/'

    [[params.social_media.items]]
    enabled = true
    title = 'Masterdon'
    icon = 'brand-mastodon'
    link = 'https://mastodon.social/@arbs'

[taxonomies]
category = "categories"
tag = "tags"
series = "series"