baseURL = 'https://arbs09.dev'

languageCode = 'en'
defaultContentLanguage = "en"

title = 'arbs09 Blog'
description = "dev blog from arbs09"
copyright = "arbs09"
auther = "arbs09"
theme = "tailwind"

enableRobotsTXT = true
enableEmoji = true
paginate = 10

[markup]
  _merge = "deep"
  [markup.highlight]
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.cjk]
        enable = true
        eastAsianLineBreaks = true
        escapedSpace = true


[params]

  keywords = "arbs09, dev blog, blog, developer, html, python, pyguard"
  subtitle = "arbs09 dev Blog"
  contentTypeName = "blog"
  showReadingTime = false
  jsonLD = true
  showAuthor = false

  [params.social]
    twitter = 'Arbs09_'

  [parms.author]
    name = "arbs09"
    email = "hi@arbs09.dev"

  [params.header]
    logo = "logo.webp"

  [params.footer]
    since = 2024
    poweredby = false

  [parms.social_media]
  [[params.social_media.items]]
    enabled = true
    title = 'Github'
    icon = 'brand-github'
    link = 'https://github.com/arbs09/'

  [[params.social_media.items]]
    enabled = true
    title = 'Instagram'
    icon = 'brand-instagram'
    link = 'https://instagram.com/arbs09/'

  [[params.social_media.items]]
    enabled = true
    title = 'Masterdon'
    icon = 'brand-mastodon'
    link = 'https://mastodon.social/@arbs'

  [[params.social_media.items]]
    enabled = true
    title = 'X'
    icon = 'brand-x'
    link = 'https://x.com/arbs09_'
  
  [[parms.pwa]]
    enabled = false
    icon = "logo.png"
    icon_sizes = [192, 512]

  [parms.pwa.manifest]
    description = "dev blog from arbs09"

[menu]
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    pageRef = "/blog"
    weight = 10
  [[menu.main]]
    identifier = "projects"
    name = "My Projects"
    pageRef = "/projects"
    weight = 0

[taxonomies]
category = "categories"
tag = "tags"
series = "series"